# Generated by Django 4.2.4 on 2023-08-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgen',
            new_name='imagen',
        ),
    ]
